name: flutter_blue
description: Bluetooth plugin for Flutter
version: 0.3.0
author: Paul DeMarco <paulmdemarco@gmail.com>
homepage: https://github.com/pauldemarco/flutter_blue

flutter:
  plugin:
    androidPackage: com.pauldemarco.flutterblue
    pluginClass: FlutterBluePlugin

dependencies:
  flutter:
    sdk: flutter
  convert: '^2.0.1'
  protobuf: '^0.7.1'


dev_dependencies:
  flutter_test:
    sdk: flutter