name: flutter_blue
description: Bluetooth plugin for Flutter
version: 0.4.0
author: Paul DeMarco <paulmdemarco@gmail.com>
homepage: https://github.com/pauldemarco/flutter_blue

flutter:
  plugin:
    androidPackage: com.pauldemarco.flutterblue
    pluginClass: FlutterBluePlugin

dependencies:
  flutter:
    sdk: flutter
  convert: '^2.0.2'
  protobuf: '^0.9.1'

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'
  flutter: '>=0.2.4 <2.0.0'