name: flutter_blue
description: Bluetooth plugin for Flutter
version: 0.5.0
author: Paul DeMarco <paulmdemarco@gmail.com>
homepage: https://github.com/pauldemarco/flutter_blue

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: '^2.1.1'
  protobuf: '^0.10.5'
  rxdart: '0.20.0'

flutter:
  plugin:
    androidPackage: com.pauldemarco.flutterblue
    pluginClass: FlutterBluePlugin

dev_dependencies:
  flutter_test:
    sdk: flutter