name: flutter_blue
description: Bluetooth plugin for Flutter
version: 0.5.0
author: Paul DeMarco <paulmdemarco@gmail.com>
homepage: https://github.com/pauldemarco/flutter_blue

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: '^2.1.1'
  protobuf: '^0.13.4'

flutter:
  plugin:
    androidPackage: com.pauldemarco.flutterblue
    pluginClass: FlutterBluePlugin

dev_dependencies:
  perfectionist: ^2.0.0
  uuid_enhanced: ^3.0.2
  flutter_test:
    sdk: flutter
