name: flutter_blue
description: Bluetooth plugin for Flutter
version: 0.2.2
author: Paul DeMarco <paulmdemarco@gmail.com>
homepage: https://github.com/pauldemarco/flutter_blue

flutter:
  plugin:
    androidPackage: com.pauldemarco.flutterblue
    pluginClass: FlutterBluePlugin

dependencies:
  flutter:
    sdk: flutter
  convert: "^2.0.1"
  protobuf: '^0.5.5'


dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: ">=1.8.0 <2.0.0"