name: flutter_blue
description:
  Flutter plugin for connecting and communicating with Bluetooth Low Energy devices,
  on Android and iOS
version: 0.8.0
homepage: https://github.com/pauldemarco/flutter_blue

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.0
  protobuf: ^2.0.0
  rxdart: ^0.27.3
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pauldemarco.flutter_blue
        pluginClass: FlutterBluePlugin
      ios:
        pluginClass: FlutterBluePlugin
      macos:
        pluginClass: FlutterBluePlugin
