name: flutter_blue
description: Bluetooth plugin for Flutter
version: 0.0.1
author: Paul DeMarco
homepage: https://github.com/pauldemarco/flutter_blue

flutter:
  plugin:
    androidPackage: com.pauldemarco.flutterblue
    pluginClass: FlutterBluePlugin

dependencies:
  flutter:
    sdk: flutter
  convert: "^2.0.1"
  protobuf: '^0.5.5'


dev_dependencies:
  flutter_test:
    sdk: flutter