name: flutter_blue
description:
  Flutter plugin for connecting and communicating with Bluetooth Low Energy devices,
  on Android and iOS
version: 0.6.2
author: Paul DeMarco <paulmdemarco@gmail.com>
homepage: https://github.com/pauldemarco/flutter_blue

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: "^2.1.1"
  protobuf: "^0.14.1"
  rxdart: "^0.22.0"

flutter:
  plugin:
    androidPackage: com.pauldemarco.flutterblue
    pluginClass: FlutterBluePlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
